---
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Artifact

on: [push, pull_request]

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: |
          echo "Debugging artifact" > ./src/resources/update-log.txt
          yarn run build -d dist -o extend-luogu.min.user.js
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist/extend-luogu.min.user.js
